gateway:
  ip: 172.18.0.4

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
   orders_is_empty: User's order is empty.
spring:
  cloud:
    config:
    allow-override: true
    override-none: true
